name: scape
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  dartz: ^0.10.1
  equatable: ^2.0.5
  responsive_builder: ^0.7.0
  dio: ^5.4.3+1
  go_router: ^14.1.2
  dotted_border: ^2.1.0
  google_fonts: ^6.2.1
  intl: ^0.20.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  shimmer: ^3.0.0
  get_storage: ^2.1.1
  url_launcher: ^6.3.0
  url_strategy: ^0.3.0
  collection: ^1.18.0
  jumping_dot: ^0.0.7
  printing: ^5.13.2
  pdf: ^3.11.1
  flutter_to_pdf: ^0.2.2
  path_provider: ^2.1.4
  flutter_widget_from_html: ^0.15.3
  qr_flutter: ^4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.10
  logger: ^2.3.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
